get_article:
    path: /article/{id}
    controller: App\Controller\ArticleController::get
    methods: GET

post_article:
    path: /article/{id}
    controller: App\Controller\ArticleController::post
    methods: POST

put_article:
    path: /article
    controller: App\Controller\ArticleController::put
    methods: PUT

get_articles:
    path: /articles
    controller: App\Controller\ArticleController::getArticles
    methods: GET